#!/usr/bin/env ruby

require 'rbbt-util'
require 'rbbt/workflow'
require 'rbbt/util/simpleopt'
require 'rbbt/util/semaphore'

options = SOPT.get("-wd--workdir* Workdir:-h--help Help:-s--sample* Check a single sample")

if options[:help]
  puts SOPT.doc
  puts <<-EOF

# GenomicTools Update

Explore a working directory to find authoritative files (as oposed to computed job results)

  EOF
  exit 0
end

one_sample = options[:sample]

Workflow.require_workflow "GenomicTools"

GenomicTools.workdir = File.expand_path(options[:workdir] || '/home/mvazquezg/git/sandbox/data_portal/CNAG')


GenomicTools.nested_workflows.each do |workflow|

  puts Log.color :magenta, "# Jobs in #{ workflow }"
  puts
  Log.debug Log.color(:magenta, "Finding all sample files for #{workflow.to_s}")
  samples = GenomicTools.all_workflow_sample_files(workflow)
  Log.debug Log.color(:magenta, "Processing #{samples.length} samples")
  samples.each do |sample,tasks|
    next if one_sample and not sample == one_sample
    puts "* " << Log.color(:blue, sample)
    tasks.each do |taskname|
      begin
        job = workflow.load_name taskname, sample
        if job.path.exists?
          status = :done
        else
          status = job.info[:status] || "waiting"
        end
      rescue
        status = :info_file_problem
      end
      status = Log.color :red, status.to_s if status.to_sym == :error or status.to_sym == :aborted
      status = Log.color :green, status.to_s if status == :done
      puts "  #{ taskname } #{status} -- #{Log.color :blue, job.path} "
    end

  end
  puts
end
