#!/usr/bin/env ruby

require 'rbbt-util'
require 'rbbt/workflow'
require 'rbbt/util/simpleopt'
require 'rbbt/util/semaphore'

options = SOPT.get("-wd--workdir* Workdir:-h--help Help")

if options[:help]
  puts SOPT.doc
  puts <<-EOF

# GenomicTools Update

Explore a working directory to find authoritative files (as oposed to computed job results)

  EOF
  exit 0
end

Workflow.require_workflow "GenomicTools"

GenomicTools.workdir = options[:workdir] || '/home/mvazquezg/git/sandbox/data_portal/CNAG'


GenomicTools.nested_workflows.each do |workflow|

  puts Log.color :magenta, "# Jobs in #{ workflow }"
  puts
  Log.debug Log.color(:magenta, "Finding all sample files for #{workflow.to_s}")
  samples = GenomicTools.all_workflow_sample_files(workflow)
  Log.debug Log.color(:magenta, "Processing #{samples.length} samples")
  samples.each do |sample,tasks|
    puts "* " << Log.color(:blue, sample)
    tasks.each do |taskname|
      job = workflow.load_name taskname, sample
      if job.path.exists?
        status = :done
      else
        status = job.status || "waiting"
      end
      status = Log.color :red, status.to_s if status == :error or status == :aborted
      status = Log.color :green, status.to_s if status == :done
      puts "  #{ taskname } -- #{status}"
    end

  end
  puts
end
